apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkwork

commonLabels:
  app.kubernetes.io/part-of: linkwork

resources:
  - namespace.yaml
  - configmap.yaml
  - initdb-configmap.yaml
  - mysql-statefulset.yaml
  - redis-statefulset.yaml
  - backend-deployment.yaml
  - gateway-deployment.yaml
  - web-deployment.yaml
