apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkwork-dev

resources:
  - ../../base

patches:
  - path: patches/backend-patch.yaml
  - path: patches/services-nodeport.yaml
  - path: patches/env-patch.yaml

images:
  - name: linkwork-backend
    newTag: latest
  - name: linkwork-mcp-gateway
    newTag: latest
  - name: linkwork-web
    newTag: latest
